---
name: Lingua-ZH-Summary
version: 0.01
author:
  - 'Cheng-Lung Sung <clsung@FreeBSD.org>'
abstract: Extract summary from Chinese text
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Net::YASA: 0
  Test::More: 0
provides:
  Lingua::ZH::Summary:
    file: lib/Lingua/ZH/Summary.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
